[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyqrypto"
version = "0.1"
authors = [ { name = "Vi Retault", email="g33kex@pm.me" } ]
description = "A library of reversible quantum circuits that perform classical cryptography"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent"
]
# [project.urls]
# "Homepage" = "https://github.com/g33kex/

[tool.pytest.ini_options]
pythonpath = "src"
